# Generated by Django 4.0.2 on 2022-02-10 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_register_table_delete_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='add_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=100)),
                ('price', models.EmailField(max_length=254)),
                ('barcode', models.IntegerField()),
                ('link', models.CharField(max_length=2000)),
            ],
        ),
        migrations.DeleteModel(
            name='register_table',
        ),
    ]
