# Generated by Django 4.0.2 on 2022-02-10 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_add_item_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_item',
            name='barcode',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='add_item',
            name='price',
            field=models.CharField(max_length=100000000),
        ),
    ]
